# NDIGITS_ETH_PRICE_ROUNDING = 2
# NDIGITS_BTC_PRICE_ROUNDING = 1

NDIGITS_PRICES_ROUNDING = {
    'BTC': 2,
    'ETH': 1,
    'ETH_USDC': 2,
}

# ------------ Order Side ------------
ORDER_SIDE_BUY = 'BUY'
ORDER_SIDE_SELL = 'SELL'
