api_key_credentials:
  key: '1efce8061b1ccc25a2bfc821ef79f958784862e0dcf92f9f766eb8a03473a378'
  # secret: '...'
  # passphrase: '...'
stark_private_key: '...'
eth_private_key: '1efce8061b1ccc25a2bfc821ef79f958784862e0dcf92f9f766eb8a03473a378'
telegram:
  bot_token: '6136357597:AAFM9LUyFkbAhq8kHhNM-YKBEgocHg8jVQM'
  chat_id: '-1001855077863'
  reporting_interval: 3600
trading_parameters:
  platform: 'dydx'
  start_date: '2023-07-01T00:00:00'
  start_deposit: 1000
  instr_1: 'ETH-USD'
  instr_2: 'BTC-USD'
  spread_operator: '/'
  grid_step: 10
  grid_direction: 'long'
  max_orders: 100
  orders_in_market: 50
  order_amount: 10
  take_profit_per_order: 0.05
  take_profit_deposit: 0.1
  refresh_interval_ms: 1000
  commission_percentage: 0.005
platforms:
  dydx_testnet:
    host: 'https://api.stage.dydx.exchange'
  
  dydx_mainnet:
    host: 'https://api.dydx.exchange'
  