credentials:
  eth_private_key: "0x1efce8061b1ccc25a2bfc821ef79f958784862e0dcf92f9f766eb8a03473a378"
  stark_private_key: "0x6ad484e0209306880be913c7c35a975baa454ebce82fc59316e17edefc696a4"
trading_parameters:
  platform: "dydx"
  mainnet: false
  start_date: "2023-07-01T00:00:00"
  instrument_1: "ETH"
  instrument_2: "BTC"
  spread_operator: "/"
  grid_direction: "long"
  start_deposit: 1000
  grid_step: 0.00005
  max_orders: 10
  orders_in_market: 4
  order_size: 25
  # take_profit_per_order: 0.05
  # take_profit_deposit: 0.1
  refresh_interval_ms: 1000
  # commission_percentage: 0.005
  limit_order_expiration_delay_seconds: 31536000
  limit_fee: 0.0015
platforms:
  dydx_testnet:
    host: "https://api.stage.dydx.exchange"
    network_id: 5
  dydx_mainnet:
    host: "https://api.dydx.exchange"
    network_id: 1
telegram:
  bot_token: "6136357597:AAFM9LUyFkbAhq8kHhNM-YKBEgocHg8jVQM"
  chat_id: "-1001855077863"
  # reporting_interval: 3600
web3_provider: "http://localhost:8545"
