account_name: "account 1"
credentials:
  dydx:
    eth_private_key: "0x1efce8061b1ccc25a2bfc821ef79f958784862e0dcf92f9f766eb8a03473a378"
    stark_private_key: "0x6ad484e0209306880be913c7c35a975baa454ebce82fc59316e17edefc696a4"
  deribit:
    client_id: "6_LsHSTh"
    client_secret: "QXHN8xGo9e2WSs0y4Z0uf1bqVmh8LKbVHtpnvuV0mn8"
trading_parameters:
  platform: "deribit"
  mainnet: false
  start_datetime: "2023-07-07 17:30:00"
  instrument_1: "ETH-PERPETUAL"
  instrument_2: "BTC-PERPETUAL"
  spread_operator: "/"
  grid_direction: "long"
  start_deposit: 1000
  grid_step: 0.00001
  max_orders: 10
  orders_in_market: 4
  order_size: 50
  take_profit_spread_delta: 0.0003
  # take_profit_deposit: 0.1
  send_updates_interval: 10 # seconds
  # commission_percentage: 0.005
  # limit_order_expiration_delay_seconds: 31536000
  # limit_fee: 0.0015
platforms:
  dydx_testnet:
    host: "https://api.stage.dydx.exchange"
    network_id: 5
  dydx_mainnet:
    host: "https://api.dydx.exchange"
    network_id: 1
  deribit_testnet:
    websocket_url: "wss://test.deribit.com/ws/api/v2"
  deribit_mainnet:
    websocket_url: "wss://www.deribit.com/ws/api/v2"
telegram:
  bot_token: "6136357597:AAFM9LUyFkbAhq8kHhNM-YKBEgocHg8jVQM"
  chat_id: "-1001855077863"
  # reporting_interval: 3600
web3_provider: "http://localhost:8545"
